### ISSUE TITLE
Cloud build is blocking the import of an extension

### ISSUE THREAD

**Issue by nedseb** [letssteam/pxt-lets-steam#48]
Our target is static packaged so theoretically, we don't need access to the cloud build system from Microsoft. All our codal targets are compiled during the build of the static version.

When we add an extension, the editor is blocking with the message "Compiling (this step can take a minute)". When we look inside the console of the browser, we see a request to the cloud build system that failed with the message "Cannot read property 'length' of null" and "The hex file is not available, please connect to the internet and try again".

When I look at the content of the JSON requested by the cloud build process (https://makecode.com/compile/12a61f211a7da7635b403649a4243bb5bc70b2f1e5c067955fa4be50ad476e97.json), it appears that the build failed but the build log seems to indicate that everything is going to the end (https://makecode.com/compile/12a61f211a7da7635b403649a4243bb5bc70b2f1e5c067955fa4be50ad476e97.log).

**Comment by pelikhan** [comment]
running ``pxt buildtarget`` does repro the error fyi

**Comment by nedseb** [comment]
In the beginning, we thought that with a static build we can avoid totally the cloud build so we use all the command of pxt in local build (https://github.com/letssteam/makecode-lets-steam/blob/main/scripts/build.sh). For us, with a static package, this issue appears only when we add an extension.

But if we resolve this particular issue, we also unlock all pxt command that always uses cloud build like `pxt checkdocs`.

**Comment by nedseb** [comment]
This issue is resolved by renaming the hex file in STM32.hex in our codal targets
